# Generated by Django 2.2.12 on 2020-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200528_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
