# Generated by Django 2.2.12 on 2020-05-31 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_content_file_image_text_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='owner',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='owner',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='titre',
        ),
    ]
