# Generated by Django 2.2.12 on 2020-05-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_parent',
            new_name='is_kinder',
        ),
    ]
